// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX3MlrkyIPo-5LrmS5N_toEoj1JkkqqIE',
    appId: '1:900505056984:web:173099c4439fc4523589ad',
    messagingSenderId: '900505056984',
    projectId: 'controlefinanceiro-c238a',
    authDomain: 'controlefinanceiro-c238a.firebaseapp.com',
    storageBucket: 'controlefinanceiro-c238a.firebasestorage.app',
    measurementId: 'G-W7Z1DJR2CX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANcZBTX0hrJVqEJVmuW075yUKTwmtj854',
    appId: '1:900505056984:ios:285a904dcf24cf663589ad',
    messagingSenderId: '900505056984',
    projectId: 'controlefinanceiro-c238a',
    storageBucket: 'controlefinanceiro-c238a.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANcZBTX0hrJVqEJVmuW075yUKTwmtj854',
    appId: '1:900505056984:ios:285a904dcf24cf663589ad',
    messagingSenderId: '900505056984',
    projectId: 'controlefinanceiro-c238a',
    storageBucket: 'controlefinanceiro-c238a.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiPUTVAnkFyNEnA-sHkb0w0pvg7a5jmsA',
    appId: '1:900505056984:android:f0fa1c6a5ac4e0363589ad',
    messagingSenderId: '900505056984',
    projectId: 'controlefinanceiro-c238a',
    storageBucket: 'controlefinanceiro-c238a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX3MlrkyIPo-5LrmS5N_toEoj1JkkqqIE',
    appId: '1:900505056984:web:552a1398b8dd2e1b3589ad',
    messagingSenderId: '900505056984',
    projectId: 'controlefinanceiro-c238a',
    authDomain: 'controlefinanceiro-c238a.firebaseapp.com',
    storageBucket: 'controlefinanceiro-c238a.firebasestorage.app',
    measurementId: 'G-ZJX5T3GCWF',
  );

}